export const roomsNames: string[] = [
	'DBL', 'TWN', 'SGL', 'DUS', 'TPL', 'QUA', 'FAM', 'BED', 'APT', 'STU',
	'SUI', 'HOM', 'DBT', 'LOD', 'ROO', 'BUN', 'VIL', 'JSU', 'CTG', 'TLN', 'CUE', 'TWH', 'CHA', 'MH'
];

export const characteristicsNames: string[] = ['ST', 'ST-1',
	'ST-2', 'ST-3', 'ST-4', 'ST-5', 'ST-6', 'ST-7', 'ST-8', 'ST-9', 'ST-10', 'ST-11', 'AS', 'AS-1', 'AS-2', 'AS-3',
	'AS-4', 'AS-5', 'AS-6', 'AS-CV', 'AS-GV', 'AS-LV', 'AS-OF', 'AS-OV', 'AS-PV', 'AS-RE', 'AS-VM', 'AS-VN', 'AS-VP',
	'2D-AS', '2Q-AS', 'AS-DB', 'AS-KG', 'AS-QN', 'AS-B1', 'AS-B2', 'AS-BL', 'AS-TR', 'AS-DX', 'BS', 'BS-1', 'BS-2',
	'BS-3', 'BS-CV', 'BS-KG', 'BS-QN', 'BS-DX', 'BS-SU', 'CB', 'CB-1', 'CB-2', 'CB-3', 'BF-CB', 'CB-CV', 'CB-HV',
	'CB-LV', 'CB-OF', 'CB-OV', 'CB-VM', '2Q-CB', 'CB-KG', 'CB-QN', 'CB-DX', 'CB-EY', 'CB-EJ', 'CB-GD', 'CB-PE',
	'CB-PI', 'CB-SU', 'CM', 'CM-1', 'CM-2', 'DP', 'DP-1', 'DP-2', 'DP-3', 'DP-4', 'DP-SU', 'DX', 'DX-1', 'DX-2',
	'DX-3', 'DX-4', 'DX-5', 'DX-6', 'DX-7', 'DX-8', 'DX-9', 'DX-10', 'BF-DX', 'BV-DX', 'CV-DX-KG', 'CV-DX', 'DX-FV',
	'DX-GV', 'DX-HV', 'DX-LK', 'DX-LV', 'DX-MV', 'DX-OF-TR', 'DX-OF', 'DX-OV', 'DX-PO', 'DX-PV', 'DX-RE', 'DX-RV',
	'DX-SF', 'DX-SS', 'DX-VG', 'DX-VL', 'BL-DX-VM', 'DX-VM', 'DX-VN', 'DX-VP', 'DX-VQ', '1B-DX', '2B-DX', '2D-DX',
	'2Q-DX', 'DX-KG', 'DX-QN', 'C2-DX', 'C4-DX', 'B1-DX', 'B1-DX-OV', 'B2-DX', 'B3-DX', 'AC-DX', 'BL-DX', 'DX-JA',
	'DX-KT', 'DX-NC', 'DX-PP', 'DX-TR', 'DX-EJ', 'DX-GD', 'DX-GR', 'DX-PE', 'DX-PI', 'DX-GV-SU', 'DX-OV-SU', 'DX-SU',
	'EJ', 'EJ-1', 'EJ-2', 'EJ-3', 'EJ-4', 'EJ-5', 'CV-EJ', 'EJ-GV', 'EJ-LV', 'EJ-OV', 'EJ-VM', 'EJ-VN', 'EJ-VQ',
	'2D-EJ', '2Q-EJ', 'EJ-KG', 'EJ-QN', 'C2-EJ', 'B1-EJ', 'B2-EJ', 'B3-EJ', 'EJ-SU', 'EY', 'EY-1', 'EY-FH', 'EY-PI',
	'FA', 'FA-1', 'C8-FA', 'GD', 'GD-1', 'GD-2', 'GD-3', 'GD-4', 'GD-5', 'GD-6', 'GD-7', 'GD-8', 'GD-SU', 'GR',
	'GR-1', 'GR-2', 'GR-3', 'CV-GR', 'GR-GV', 'GR-OV', 'GR-RE', 'GR-VM', 'GR-KG', 'GR-QN', 'IN', 'IN-1', 'IN-2',
	'LX', 'LX-1', 'LX-2', 'LX-3', 'LX-4', 'LX-5', 'LX-6', 'CV-LX', 'LX-OV', 'LX-PO', 'LX-VM', 'B1-LX', 'B2-LX',
	'MQ', 'MQ-1', 'C8-MQ', 'OM', 'OM-1', 'OM-2', 'OM-VM', 'PE', 'PE-1', 'PE-2', 'PE-3', 'PE-4', 'PE-5', 'CV-PE',
	'HV-PE', 'OF-PE', 'OV-PE', 'PE-RV', 'PE-VM', 'KG-PE', 'PE-QN', 'B1-PE', 'B2-PE', 'PI', 'PI-1', 'PI-2', 'PI-3',
	'PI-4', 'PI-5', 'BF-PI', 'CV-PI', 'GV-PI', 'OF-PI', 'OV-PI', 'PI-VM', 'KG-PI', 'PI-QN', 'B1-PI', 'PI-SU', 'PR',
	'PR-1', 'PR-2', 'PT', 'PT-1', 'PT-2', 'RO', 'RO-1', 'RO-2', 'SD', 'SU', 'SU-1', 'SU-2', 'SU-3', 'SU-4', 'SU-5',
	'SU-6', 'BF-SU', 'BV-SU', 'CV-SU', 'GV-SU', 'HV-SU', 'LK-SU', 'LV-SU', 'OF-SU', 'OV-SU', 'PO-SU', 'PV-SU', 'RV-SU',
	'SF-SU', 'SS-SU', 'SU-VL', 'SU-VM', 'SU-VN', 'SU-VP', 'SU-WV', '2D-SU', 'DB-SU', 'KG-SU', 'QN-SU', 'C2-SU',
	'C3-SU', 'C4-SU', 'B1-SU', 'B2-SU', 'B3-SU', 'B4-SU', 'B5-SU', 'AC-SU', 'BL-SU', 'PP-SU', 'SU-TR', 'Z1', 'Z1-1',
	'Z1-2', 'BF', 'BF-1', 'BF-2', 'BF-3', 'BF-4', 'BF-5', 'B2-BF', 'BV', 'BV-1', 'BV-2', 'BV-KG', 'CV', 'CV-1', 'CV-2',
	'CV-3', 'CV-4', 'CV-5', '2B-CV', '2D-CV', '2Q-CV', 'CV-KG', 'CV-QN', 'B1-CV', 'B2-CV', 'FV', 'FV-1', 'FV-2',
	'B1-FV', 'GV', 'GV-1', 'GV-2', 'GV-3', 'GV-4', 'GV-5', 'GV-6', '2Q-GV', 'GV-KG', 'C2-GV', 'B1-GV', 'B2-GV',
	'BL-GV', 'HV', 'HV-1', 'HV-2', 'HV-3', 'HV-4', 'LK', 'LK-1', 'LK-2', 'LK-3', 'LV', 'LV-1', 'LV-2', 'LV-3',
	'MV', 'MV-1', 'MV-2', 'OF', 'OF-1', 'OF-2', 'OF-3', 'OF-4', 'OF-5', 'OF-6', 'OF-7', '2D-OF', 'KG-OF', 'B1-OF',
	'B2-OF', 'BL-OF', 'OV', 'OV-1', 'OV-2', 'OV-3', 'OV-4', 'OV-5', 'OV-6', 'OV-7', 'OV-8', '2D-OV', '2Q-OV',
	'KG-OV', 'OV-QN', 'B1-OV', 'B2-OV', 'B3-OV', 'BL-OV', 'HM-OV', 'PO', 'PO-1', 'PO-2', 'PO-3', 'PO-4', '2D-PO',
	'KG-PO', 'PO-QN', 'B1-PO', 'B2-PO', 'PS', 'PS-1', 'PV', 'PV-1', 'PV-2', 'PV-3', 'PV-4', 'BL-PV', 'RE', 'RE-1',
	'RV', 'RV-1', 'RV-2', 'RV-3', 'SF', 'SF-1', 'SF-2', 'SS', 'SS-1', 'SS-2', 'SS-3', 'B1-SS', 'B2-SS', 'BL-SS',
	'VG', 'VG-1', 'VG-2', 'VL', 'VL-1', 'VL-2', 'VL-3', 'VM', 'VM-1', 'VM-2', 'VM-3', 'VM-4', 'VM-5', 'VM-6',
	'KG-VM', 'C2-VM', 'C3-VM', 'C4-VM', 'C5-VM', 'B1-VM', 'B2-VM', 'B3-VM', 'AC-VM', 'BL-VM', 'HM-VM', 'PP-VM',
	'TR-VM', 'VM-VP', 'VN', 'VN-1', 'VN-2', 'VN-3', 'VP', 'VP-1', 'VP-2', 'VP-3', 'VP-4', 'VP-5', '2D-VP', 'KG-VP',
	'B1-VP', 'B2-VP', 'VQ', 'VQ-1', 'WV', 'WV-1', 'WV-2', 'WV-3', '1B', '1B-1', '2B', '2B-1', '2B-2', '2D', '2D-1',
	'2D-2', '2D-3', '2D-4', '2D-5', '2D-6', '2D-B1', '2D-NM', '2K', '2K-1', '2Q', '2Q-1', '2Q-2', '2Q-3', '2Q-4',
	'2Q-5', '2Q-6', '2Q-B1', '2Q-NM', '3B', 'BK', 'BK-1', 'BK-FH', 'DB', 'DB-1', 'DB-2', 'DB-3', 'KG', 'KG-1', 'KG-2',
	'KG-3', 'KG-4', 'KG-5', 'KG-6', 'KG-7', 'KG-8', 'B1-KG', 'B2-KG', 'JA-KG', 'KG-NM', 'QN', 'QN-1', 'QN-2', 'QN-3',
	'QN-4', 'QN-5', 'QN-6', 'B2-QN', 'NM-QN', 'C1', 'C1-1', 'C1-2', 'C1-3', 'C1-4', 'B1-C1', 'C2', 'C2-1', 'C2-2',
	'C2-3', 'C2-4', 'B1-C2', 'B2-C2', 'AC-C2', 'C3', 'C3-1', 'C3-2', 'C3-3', 'B1-C3', 'B2-C3', 'C4', 'C4-1', 'C4-2',
	'C4-3', 'C4-4', 'B1-C4', 'B2-C4', 'B3-C4', 'C5', 'C5-1', 'C5-2', 'B1-C5', 'B2-C5', 'B3-C5', 'C5-FH', 'C6', 'C6-1',
	'C6-2', 'C6-3', 'C6-4', 'B1-C6', 'B2-C6', 'B3-C6', 'C6-FH', 'C7', 'C7-1', 'B2-C7', 'B3-C7', 'C8', 'C8-1', 'B2-C8',
	'B3-C8', 'B4-C8', 'C8-FH', 'C9', 'B4-C9', 'C10', 'B1', 'B1-1', 'B1-2', 'B1-3', 'B1-4', 'B1-5', 'B1-6', 'B1-7',
	'B1-8', 'B1-9', 'B1-10', '1W-B1', '2W-B1', '3W-B1', 'AC-B1', 'B1-TR', 'B2', 'B2-1', 'B2-2', 'B2-3', 'B2-4',
	'B2-5', 'B2-6', '1W-B2', '2W-B2', '3W-B2', 'B2-XW', 'AC-B2', 'B2-NM', 'B2-PP', 'B2-TR', 'B3', 'B3-1', 'B3-2',
	'B3-3', 'B3-4', 'B3-5', 'B3-6', '1W-B3', '2W-B3', '3W-B3', 'B3-XW', 'AC-B3', 'B3-PP', 'B4', 'B4-1', 'B4-2',
	'B4-3', 'B4-4', '1W-B4', '2W-B4', '3W-B4', 'B4-XW', 'B4-PP', 'B5', 'B5-1', '2W-B5', '3W-B5', 'B5-XW', 'B5-PP',
	'2W-B6', '3W-B6', 'B6-XW', 'B6-PP', 'B7-PP', 'B7-XW', 'B8-PP', 'B8-XW', 'B9-XW', 'BB-10', 'BB-11', 'BB-12', 'BB-13',
	'AC', 'AC-1', 'AX', 'AX-1', 'BL', 'BL-1', 'BL-2', 'BL-3', 'BL-4', 'BL-5', 'BL-6', 'FH', 'FH-1', 'FH-2', 'FH-3',
	'HM', 'HM-1', 'HM-2', 'HM-3', 'JA', 'JA-1', 'JA-2', 'JA-3', 'JA-4', 'JA-5', 'JA-6', 'JA-7', 'KT', 'KT-1', 'KT-2',
	'KT-3', 'NC', 'NM', 'NM-1', 'NM-2', 'NM-3', 'PP', 'PP-1', 'PP-2', 'PP-3', 'TR', 'TR-1', 'TR-2', 'TR-3'];
