export const roomsNames: any[] = [
  {name: 'Room1', id: 'Id-1'},
  {name: 'Room2', id: 'Id-2'},
  {name: 'Room3', id: 'Id-3'},
  {name: 'Room4', id: 'Id-4'},
  {name: 'Room5', id: 'Id-5'},
  {name: 'Room6', id: 'Id-6'},
  {name: 'Room7', id: 'Id-7'},
  {name: 'Room8', id: 'Id-8'},
  {name: 'Room9', id: 'Id-9'},
  {name: 'Room10', id: 'Id-10'},
  {name: 'Room11', id: 'Id-11'},
  {name: 'Room12', id: 'Id-12'},
  {name: 'Room13', id: 'Id-13'},
  {name: 'Room14', id: 'Id-14'},
  {name: 'Room15', id: 'Id-15'},
  {name: 'Room16', id: 'Id-16'},
  {name: 'Room17', id: 'Id-17'},
];

export const characteristicsNames: any[] = [
  {name: 'C1', id: 'C1'},
  {name: 'C2', id: 'C2'},
  {name: 'C3', id: 'C3'},
  {name: 'C4', id: 'C4'},
  {name: 'C5', id: 'C5'},
  {name: 'C6', id: 'C6'},
  {name: 'C7', id: 'C7'},
  {name: 'C8', id: 'C8'},
  {name: 'C9', id: 'C9'},
  {name: 'C10', id: 'C10'},
  {name: 'C11', id: 'C11'},
  {name: 'C12', id: 'C12'},
  {name: 'C13', id: 'C13'},
];
