export interface ISvgIcons {
	excel: string;
	left_arrow_in_box: string;
	right_arrow_in_box: string;
	hotel: string;
	calendar: string;
	noResults: string;
	search: string;
	childAge: string;
	next: string;
	back: string;
	round_close: string;
	arrowDown: string;
	save: string;
	bcSeparator: string;
	client: string;
	chain: string;
	matrix: string;
	modify_edit: string;
	modify_delete: string;
	modify_duplicate: string;
	modify_history: string;
	regular_hotel: string;
	bin: string;
	info: string;
	cancel: string;
	checkMark: string;
	close_toast: string;
	plus: string;
	eye: string;
	season_calendar: string;
	down_arrow_collapse: string;
	right_arrow_display: string;
	disconnect: string;
	link: string;
	moon: string;
	contract: string;
	errorTriangle: string;
	technicalErrorTriangle: string;
	downloadIcon: string;
	publish: string;
  fail: string;
  success: string;
  pencil: string;
  exclamationMark: string;
}

export const SVG_ICONS: ISvgIcons = {
	excel: 'excel',
	left_arrow_in_box: 'left_arrow_in_box',
	right_arrow_in_box: 'right_arrow_in_box',
	hotel: 'hotelCode',
	calendar: 'calendar',
	noResults: 'noResults',
	search: 'search',
	next: 'next',
	back: 'back',
	round_close: 'round_close',
	childAge: 'childAge',
	arrowDown: 'arrowDown',
	save: 'save',
	bcSeparator: 'bcSeparator',
	client: 'client',
	chain: 'chain',
	matrix: 'matrix',
	modify_edit: 'modify_edit',
	modify_delete: 'modify_delete',
	modify_duplicate: 'modify_duplicate',
	modify_history: 'modify_history',
	regular_hotel: 'regular_hotel',
	bin: 'bin',
	info: 'info',
	cancel: 'cancel',
	checkMark: 'checkMark',
	close_toast: 'close_toast',
	plus: 'plus',
	eye: 'eye',
	season_calendar: 'season_calendar',
	down_arrow_collapse: 'down_arrow_collapse',
	right_arrow_display: 'right_arrow_display',
	disconnect: 'disconnect',
	link: 'link',
	moon: 'moon',
	contract: 'contract',
	errorTriangle: 'errorTriangle',
	technicalErrorTriangle: 'technicalErrorTriangle',
	downloadIcon: 'downloadIcon',
	publish: 'publish',
  fail: 'fail',
  success: 'success',
  pencil: 'pencil',
  exclamationMark: 'exclamationMark'
};
